title: github learning
author: winmau310
email: ithinkican9102@gmail.com
description: this is a webpage to help to learn githubs programing

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  winmau310 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
